### ISSUE TITLE
No "Meaning" option showing

### ISSUE THREAD

**Issue by E0697** [tirkarthi/NotificationDictionary#25]
I tried both the F-Droid and Google Play versions. Downloaded initial database, but still the "meaning" option doesn't show up in the context menu!

**Comment by tirkarthi** [comment]
Can you please let me know the app you are trying? I get the menu in Chrome. Some apps override like adobe reader could override long press to give custom menu for cut, copy, paste etc.

**Comment by E0697** [comment]
Well I tried Mull (Firefox), Brave, Vivaldi. It doesn't show up in any of them. I don't use Chrome but I'll install it and test.

**Comment by tirkarthi** [comment]
I just tried below URL and able to select words not links to show "meaning". Can you please add a URL you are trying or possibly a short video? Also sometimes meaning is not visible directly and should be accessed in the context menu after cut, copy, paste using the triple dot hamburger menu. Tested in latest Brave and Firefox.

https://en.m.wikipedia.org/wiki/Main_Page

**Comment by E0697** [comment]
Here's a video:

https://user-images.githubusercontent.com/66939100/158573564-caadde65-8215-4fd7-8193-7e9516075e42.mp4

Is it maybe because the context menu is overpopulated?
I had the Dictonary.com app installed earlier, and it would show a "Dictionary" option alongside the ones shown in the video.

**Comment by E0697** [comment]
The issue has been resolved after Android 12 update.

**Comment by tirkarthi** [comment]
Thanks for the update @E0697

**Comment by E0697** [comment]
> Thanks for the update @E0697 

Sure thing! The app is very useful, thank you!

**Comment by E0697** [comment]
Sure thing!
