### ISSUE TITLE
Other languages?

### ISSUE THREAD

**Issue by yaoberh** [tirkarthi/NotificationDictionary#26]
Can I manually add other languages? What do I need to download to do this?

**Comment by tirkarthi** [comment]
Currently adding languages need to be done in code and the relevant database in CDN. The relevant code is here https://github.com/tirkarthi/NotificationDictionary/blob/63daecb8e7374c1a153212e0210daa73fdff7377/app/src/main/java/com/xtreak/notificationdictionary/MainActivity.kt#L372

**Comment by yaoberh** [comment]
Cool! Thanks :)
