### ISSUE TITLE
[BUG] Wrong character encoding 

### ISSUE THREAD

**Issue by loulou64490** [tirkarthi/NotificationDictionary#40]
### Screenshot
![Screenshot_20231001_201158_Notification Dictionary](https://github.com/tirkarthi/NotificationDictionary/assets/102870297/40082060-22ce-47c1-a0dd-200e3b566159)
![Screenshot_20231001_201705_Brave](https://github.com/tirkarthi/NotificationDictionary/assets/102870297/03943ae2-ea0d-4694-a5fc-7de7a7b3591b)
### [System info (bug report)](https://uploadnow.io/f/QccpwNv)

**Comment by tirkarthi** [comment]
Hi @loulou64490 , thanks for the bug report. Can you please share the language used in the mobile? Can you please share the expected encoding? The relevant values are present here : 

https://github.com/tirkarthi/NotificationDictionary/blob/main/app/src/main/res/values-fr/strings.xml

**Comment by loulou64490** [comment]
[Expected encoding for french](https://pastebin.com/raw/et8xM7GJ)

**Comment by loulou64490** [comment]
[](https://github.com/tirkarthi/NotificationDictionary/pull/44)
