### ISSUE TITLE
Release apk in github

### ISSUE THREAD

**Issue by chromer030** [tirkarthi/NotificationDictionary#47]
Please provide release apk in github.

**Comment by tirkarthi** [comment]
Thanks for the report. Currently, the process is manual and generates aab file from android studio to let google create apk files. I will try to upload the apk files signed in github and hopefully add automation using fastlane or something similar in future but currently not prioritizing it. For raw APK files please also use fdroid in case google play is not appropriate for you.

Thanks

**Comment by chromer030** [comment]
Thanks for considering the request.

The reason for opening this issue is Fdroid release the update very late.

Current version on Fdroid : Version 0.0.18 
Current released version on Github : 0.0.21

**Comment by tirkarthi** [comment]
Yes, Fdroid builds are queued after checking for update. I noticed sometimes they are batched together with other apps where one build failure in the batch causes build to fail without building other apps. I have released v0.0.22 now. Please test if the apk works.

https://github.com/tirkarthi/NotificationDictionary/releases/tag/v0.0.22

Thanks

**Comment by chromer030** [comment]
Thanks for the APK; it's working.

F-Droid is great, but it does have some limitations.
It tends to update apps later than other sources. Additionally, it lacks support for incremental updates and doesn't provide a section or feature for delivering split APKs.
This can significantly increase the app size, both during download and installation. For example, my device is arm64, but I also need to have x86 libraries on my device.

**Comment by chromer030** [comment]
We can close this issue as it's fixed, thanks for consideration.

**Comment by tirkarthi** [comment]
Thanks @chromer030
