### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by saltsoftdrink** [tirkarthi/NotificationDictionary#59]
Add material themed icon

**Comment by tirkarthi** [comment]
@saltsoftdrink Thanks for opening this issue. I have less experience with respect to theming and icons. Can you please add some links to docs or sample icons in mind or a description of the changes you are proposing?

**Comment by tirkarthi** [comment]
Thanks for the links. With regards to adaptive icon as per docs I have icon and roundIcon mentioned in manifest file. I was using Nova launcher where I tried to change the color palette to something like green with applying the change to icons and it didn't change anything. On switching to Samsung launcher I can see apps like gmail switch to green background in the background. But the notification dictionary app is still in original form. If I understand the feature it's to use the themed colors and adapt the app icon to use that them. Please correct me if I am wrong here.

https://proandroiddev.com/implement-themed-icons-android-13-d20b89233681
https://medium.com/@BitMavrick/monochrome-launcher-icon-for-android-app-213543a0cb91

There was also a request for monochrome icon in another issue not sure if it's the same : https://github.com/tirkarthi/NotificationDictionary/issues/51

**Comment by tirkarthi** [comment]
I haven't started working on it yet. I will update if there is any development.
