### ISSUE TITLE
It's been 4+ months add a update 

### ISSUE THREAD

**Issue by saltsoftdrink** [tirkarthi/NotificationDictionary#64]

**Comment by tirkarthi** [comment]
A couple of PRs were merged. I am working on https://github.com/tirkarthi/NotificationDictionary/pull/63 which has been requested a lot. There is no ETA as of now since the feature is a major one but progressing along well.

**Comment by tirkarthi** [comment]
v0.0.23 has been released with apk. Please test and provide feedback. The google play version is in review.

https://github.com/tirkarthi/NotificationDictionary/releases/tag/v0.0.23

**Comment by tirkarthi** [comment]
v0.0.23 is now available in Google play : https://play.google.com/store/apps/details?id=com.xtreak.notificationdictionary . Closing the ticket. Thanks.
